"""apex initial schema

Revision ID: 75b01a0897a7
Revises: 
Create Date: 2026-08-31 11:42:37.183195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75b01a0897a7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canonical_trims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=96), nullable=False),
    sa.Column('raw_spec', sa.String(length=128), nullable=False),
    sa.Column('canonical_spec', sa.String(length=128), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('make', 'model', 'raw_spec', name='uq_trim_make_model_raw')
    )
    op.create_index('ix_trim_lookup', 'canonical_trims', ['make', 'model', 'raw_spec'], unique=False)
    op.create_table('dealers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['dealers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dealers_group_id'), 'dealers', ['group_id'], unique=False)
    op.create_index(op.f('ix_dealers_name'), 'dealers', ['name'], unique=False)
    op.create_index(op.f('ix_dealers_region'), 'dealers', ['region'], unique=False)
    op.create_table('dealer_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_name', sa.String(length=255), nullable=False),
    sa.Column('dealer_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dealer_aliases_dealer_id'), 'dealer_aliases', ['dealer_id'], unique=False)
    op.create_index(op.f('ix_dealer_aliases_raw_name'), 'dealer_aliases', ['raw_name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=64), nullable=True),
    sa.Column('dealer_id', sa.Integer(), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('phone_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subscription_status', sa.String(length=24), nullable=True),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signup_source', sa.String(length=16), nullable=True),
    sa.Column('assistant_questions_used', sa.Integer(), nullable=False),
    sa.Column('assistant_period_start', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_dealer_id'), 'users', ['dealer_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_stripe_customer_id'), 'users', ['stripe_customer_id'], unique=False)
    op.create_index(op.f('ix_users_subscription_status'), 'users', ['subscription_status'], unique=False)
    op.create_table('verification_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('code', sa.String(length=12), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_codes_user_id'), 'verification_codes', ['user_id'], unique=False)
    op.create_table('weekly_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_ending', sa.Date(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('rows_total', sa.Integer(), nullable=False),
    sa.Column('rows_inserted', sa.Integer(), nullable=False),
    sa.Column('rows_rejected', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sales_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekly_snapshots_status'), 'weekly_snapshots', ['status'], unique=False)
    op.create_index(op.f('ix_weekly_snapshots_week_ending'), 'weekly_snapshots', ['week_ending'], unique=True)
    op.create_table('ingest_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('week_ending', sa.Date(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('progress_pct', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=True),
    sa.Column('rows_total', sa.Integer(), nullable=True),
    sa.Column('rows_inserted', sa.Integer(), nullable=True),
    sa.Column('rows_rejected', sa.Integer(), nullable=True),
    sa.Column('sales_derived', sa.Integer(), nullable=True),
    sa.Column('relists_flagged', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('audit_warnings', sa.Text(), nullable=True),
    sa.Column('snapshot_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['weekly_snapshots.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingest_jobs_status'), 'ingest_jobs', ['status'], unique=False)
    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('dealer_id', sa.Integer(), nullable=True),
    sa.Column('week_ending', sa.Date(), nullable=False),
    sa.Column('is_held', sa.Boolean(), nullable=False),
    sa.Column('hold_reason', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('link', sa.String(length=1024), nullable=True),
    sa.Column('vin', sa.String(length=32), nullable=True),
    sa.Column('number_plate', sa.String(length=16), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('make', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=96), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('spec', sa.String(length=128), nullable=True),
    sa.Column('spec_canonical', sa.String(length=128), nullable=True),
    sa.Column('engine_litres', sa.Float(), nullable=True),
    sa.Column('body_style', sa.String(length=32), nullable=True),
    sa.Column('seats', sa.Integer(), nullable=True),
    sa.Column('engine_cc', sa.Integer(), nullable=True),
    sa.Column('fuel_type', sa.String(length=24), nullable=True),
    sa.Column('transmission', sa.String(length=24), nullable=True),
    sa.Column('fourwd', sa.String(length=8), nullable=True),
    sa.Column('ext_color', sa.String(length=32), nullable=True),
    sa.Column('kms', sa.Integer(), nullable=True),
    sa.Column('kms_category', sa.String(length=32), nullable=True),
    sa.Column('imp_history', sa.String(length=16), nullable=True),
    sa.Column('location', sa.String(length=96), nullable=True),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('price_type', sa.String(length=32), nullable=True),
    sa.Column('est_price', sa.Float(), nullable=True),
    sa.Column('number_of_days_listed', sa.Integer(), nullable=True),
    sa.Column('listed_category', sa.String(length=16), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('watchlisted', sa.Integer(), nullable=True),
    sa.Column('overseas', sa.Boolean(), nullable=True),
    sa.Column('quick_sale', sa.Boolean(), nullable=True),
    sa.Column('upgrading', sa.Boolean(), nullable=True),
    sa.Column('hard_lid', sa.Boolean(), nullable=True),
    sa.Column('canopy', sa.Boolean(), nullable=True),
    sa.Column('tow_bar', sa.Boolean(), nullable=True),
    sa.Column('eighteen_wheels', sa.Boolean(), nullable=True),
    sa.Column('twenty_wheels', sa.Boolean(), nullable=True),
    sa.Column('twentyone_wheels', sa.Boolean(), nullable=True),
    sa.Column('twentytwo_wheels', sa.Boolean(), nullable=True),
    sa.Column('dealer_name_raw', sa.String(length=255), nullable=True),
    sa.Column('dealer_address', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealers.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['weekly_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listings_body_style'), 'listings', ['body_style'], unique=False)
    op.create_index('ix_listings_comp', 'listings', ['week_ending', 'make', 'model', 'year'], unique=False)
    op.create_index(op.f('ix_listings_dealer_id'), 'listings', ['dealer_id'], unique=False)
    op.create_index('ix_listings_dealer_week', 'listings', ['dealer_id', 'week_ending'], unique=False)
    op.create_index(op.f('ix_listings_engine_litres'), 'listings', ['engine_litres'], unique=False)
    op.create_index(op.f('ix_listings_fuel_type'), 'listings', ['fuel_type'], unique=False)
    op.create_index(op.f('ix_listings_is_held'), 'listings', ['is_held'], unique=False)
    op.create_index(op.f('ix_listings_kms'), 'listings', ['kms'], unique=False)
    op.create_index(op.f('ix_listings_listed_category'), 'listings', ['listed_category'], unique=False)
    op.create_index(op.f('ix_listings_make'), 'listings', ['make'], unique=False)
    op.create_index(op.f('ix_listings_model'), 'listings', ['model'], unique=False)
    op.create_index(op.f('ix_listings_number_of_days_listed'), 'listings', ['number_of_days_listed'], unique=False)
    op.create_index(op.f('ix_listings_number_plate'), 'listings', ['number_plate'], unique=False)
    op.create_index(op.f('ix_listings_price'), 'listings', ['price'], unique=False)
    op.create_index(op.f('ix_listings_region'), 'listings', ['region'], unique=False)
    op.create_index('ix_listings_snap_plate', 'listings', ['snapshot_id', 'number_plate'], unique=False)
    op.create_index('ix_listings_snap_vin', 'listings', ['snapshot_id', 'vin'], unique=False)
    op.create_index(op.f('ix_listings_snapshot_id'), 'listings', ['snapshot_id'], unique=False)
    op.create_index(op.f('ix_listings_spec_canonical'), 'listings', ['spec_canonical'], unique=False)
    op.create_index(op.f('ix_listings_vin'), 'listings', ['vin'], unique=False)
    op.create_index(op.f('ix_listings_week_ending'), 'listings', ['week_ending'], unique=False)
    op.create_index(op.f('ix_listings_year'), 'listings', ['year'], unique=False)
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dealer_id', sa.Integer(), nullable=True),
    sa.Column('last_seen_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('sold_week', sa.Date(), nullable=False),
    sa.Column('sold_via', sa.String(length=8), nullable=True),
    sa.Column('is_provisional', sa.Boolean(), nullable=False),
    sa.Column('is_relist', sa.Boolean(), nullable=False),
    sa.Column('relisted_week', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('link', sa.String(length=1024), nullable=True),
    sa.Column('vin', sa.String(length=32), nullable=True),
    sa.Column('number_plate', sa.String(length=16), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('make', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=96), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('spec', sa.String(length=128), nullable=True),
    sa.Column('spec_canonical', sa.String(length=128), nullable=True),
    sa.Column('engine_litres', sa.Float(), nullable=True),
    sa.Column('body_style', sa.String(length=32), nullable=True),
    sa.Column('seats', sa.Integer(), nullable=True),
    sa.Column('engine_cc', sa.Integer(), nullable=True),
    sa.Column('fuel_type', sa.String(length=24), nullable=True),
    sa.Column('transmission', sa.String(length=24), nullable=True),
    sa.Column('fourwd', sa.String(length=8), nullable=True),
    sa.Column('ext_color', sa.String(length=32), nullable=True),
    sa.Column('kms', sa.Integer(), nullable=True),
    sa.Column('kms_category', sa.String(length=32), nullable=True),
    sa.Column('imp_history', sa.String(length=16), nullable=True),
    sa.Column('location', sa.String(length=96), nullable=True),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('price_type', sa.String(length=32), nullable=True),
    sa.Column('est_price', sa.Float(), nullable=True),
    sa.Column('number_of_days_listed', sa.Integer(), nullable=True),
    sa.Column('listed_category', sa.String(length=16), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('watchlisted', sa.Integer(), nullable=True),
    sa.Column('overseas', sa.Boolean(), nullable=True),
    sa.Column('quick_sale', sa.Boolean(), nullable=True),
    sa.Column('upgrading', sa.Boolean(), nullable=True),
    sa.Column('hard_lid', sa.Boolean(), nullable=True),
    sa.Column('canopy', sa.Boolean(), nullable=True),
    sa.Column('tow_bar', sa.Boolean(), nullable=True),
    sa.Column('eighteen_wheels', sa.Boolean(), nullable=True),
    sa.Column('twenty_wheels', sa.Boolean(), nullable=True),
    sa.Column('twentyone_wheels', sa.Boolean(), nullable=True),
    sa.Column('twentytwo_wheels', sa.Boolean(), nullable=True),
    sa.Column('dealer_name_raw', sa.String(length=255), nullable=True),
    sa.Column('dealer_address', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealers.id'], ),
    sa.ForeignKeyConstraint(['last_seen_snapshot_id'], ['weekly_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_body_style'), 'sales', ['body_style'], unique=False)
    op.create_index('ix_sales_comp', 'sales', ['sold_week', 'make', 'model', 'year'], unique=False)
    op.create_index(op.f('ix_sales_dealer_id'), 'sales', ['dealer_id'], unique=False)
    op.create_index('ix_sales_dealer_week', 'sales', ['dealer_id', 'sold_week'], unique=False)
    op.create_index(op.f('ix_sales_engine_litres'), 'sales', ['engine_litres'], unique=False)
    op.create_index(op.f('ix_sales_fuel_type'), 'sales', ['fuel_type'], unique=False)
    op.create_index(op.f('ix_sales_is_provisional'), 'sales', ['is_provisional'], unique=False)
    op.create_index(op.f('ix_sales_is_relist'), 'sales', ['is_relist'], unique=False)
    op.create_index(op.f('ix_sales_kms'), 'sales', ['kms'], unique=False)
    op.create_index(op.f('ix_sales_last_seen_snapshot_id'), 'sales', ['last_seen_snapshot_id'], unique=False)
    op.create_index(op.f('ix_sales_listed_category'), 'sales', ['listed_category'], unique=False)
    op.create_index(op.f('ix_sales_make'), 'sales', ['make'], unique=False)
    op.create_index(op.f('ix_sales_model'), 'sales', ['model'], unique=False)
    op.create_index(op.f('ix_sales_number_of_days_listed'), 'sales', ['number_of_days_listed'], unique=False)
    op.create_index(op.f('ix_sales_number_plate'), 'sales', ['number_plate'], unique=False)
    op.create_index(op.f('ix_sales_price'), 'sales', ['price'], unique=False)
    op.create_index(op.f('ix_sales_region'), 'sales', ['region'], unique=False)
    op.create_index(op.f('ix_sales_sold_week'), 'sales', ['sold_week'], unique=False)
    op.create_index(op.f('ix_sales_spec_canonical'), 'sales', ['spec_canonical'], unique=False)
    op.create_index(op.f('ix_sales_vin'), 'sales', ['vin'], unique=False)
    op.create_index(op.f('ix_sales_year'), 'sales', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_year'), table_name='sales')
    op.drop_index(op.f('ix_sales_vin'), table_name='sales')
    op.drop_index(op.f('ix_sales_spec_canonical'), table_name='sales')
    op.drop_index(op.f('ix_sales_sold_week'), table_name='sales')
    op.drop_index(op.f('ix_sales_region'), table_name='sales')
    op.drop_index(op.f('ix_sales_price'), table_name='sales')
    op.drop_index(op.f('ix_sales_number_plate'), table_name='sales')
    op.drop_index(op.f('ix_sales_number_of_days_listed'), table_name='sales')
    op.drop_index(op.f('ix_sales_model'), table_name='sales')
    op.drop_index(op.f('ix_sales_make'), table_name='sales')
    op.drop_index(op.f('ix_sales_listed_category'), table_name='sales')
    op.drop_index(op.f('ix_sales_last_seen_snapshot_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_kms'), table_name='sales')
    op.drop_index(op.f('ix_sales_is_relist'), table_name='sales')
    op.drop_index(op.f('ix_sales_is_provisional'), table_name='sales')
    op.drop_index(op.f('ix_sales_fuel_type'), table_name='sales')
    op.drop_index(op.f('ix_sales_engine_litres'), table_name='sales')
    op.drop_index('ix_sales_dealer_week', table_name='sales')
    op.drop_index(op.f('ix_sales_dealer_id'), table_name='sales')
    op.drop_index('ix_sales_comp', table_name='sales')
    op.drop_index(op.f('ix_sales_body_style'), table_name='sales')
    op.drop_table('sales')
    op.drop_index(op.f('ix_listings_year'), table_name='listings')
    op.drop_index(op.f('ix_listings_week_ending'), table_name='listings')
    op.drop_index(op.f('ix_listings_vin'), table_name='listings')
    op.drop_index(op.f('ix_listings_spec_canonical'), table_name='listings')
    op.drop_index(op.f('ix_listings_snapshot_id'), table_name='listings')
    op.drop_index('ix_listings_snap_vin', table_name='listings')
    op.drop_index('ix_listings_snap_plate', table_name='listings')
    op.drop_index(op.f('ix_listings_region'), table_name='listings')
    op.drop_index(op.f('ix_listings_price'), table_name='listings')
    op.drop_index(op.f('ix_listings_number_plate'), table_name='listings')
    op.drop_index(op.f('ix_listings_number_of_days_listed'), table_name='listings')
    op.drop_index(op.f('ix_listings_model'), table_name='listings')
    op.drop_index(op.f('ix_listings_make'), table_name='listings')
    op.drop_index(op.f('ix_listings_listed_category'), table_name='listings')
    op.drop_index(op.f('ix_listings_kms'), table_name='listings')
    op.drop_index(op.f('ix_listings_is_held'), table_name='listings')
    op.drop_index(op.f('ix_listings_fuel_type'), table_name='listings')
    op.drop_index(op.f('ix_listings_engine_litres'), table_name='listings')
    op.drop_index('ix_listings_dealer_week', table_name='listings')
    op.drop_index(op.f('ix_listings_dealer_id'), table_name='listings')
    op.drop_index('ix_listings_comp', table_name='listings')
    op.drop_index(op.f('ix_listings_body_style'), table_name='listings')
    op.drop_table('listings')
    op.drop_index(op.f('ix_ingest_jobs_status'), table_name='ingest_jobs')
    op.drop_table('ingest_jobs')
    op.drop_index(op.f('ix_weekly_snapshots_week_ending'), table_name='weekly_snapshots')
    op.drop_index(op.f('ix_weekly_snapshots_status'), table_name='weekly_snapshots')
    op.drop_table('weekly_snapshots')
    op.drop_index(op.f('ix_verification_codes_user_id'), table_name='verification_codes')
    op.drop_table('verification_codes')
    op.drop_index(op.f('ix_users_subscription_status'), table_name='users')
    op.drop_index(op.f('ix_users_stripe_customer_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_dealer_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_dealer_aliases_raw_name'), table_name='dealer_aliases')
    op.drop_index(op.f('ix_dealer_aliases_dealer_id'), table_name='dealer_aliases')
    op.drop_table('dealer_aliases')
    op.drop_index(op.f('ix_dealers_region'), table_name='dealers')
    op.drop_index(op.f('ix_dealers_name'), table_name='dealers')
    op.drop_index(op.f('ix_dealers_group_id'), table_name='dealers')
    op.drop_table('dealers')
    op.drop_index('ix_trim_lookup', table_name='canonical_trims')
    op.drop_table('canonical_trims')
    # ### end Alembic commands ###
