"""listing valuation columns

Revision ID: 797c95261056
Revises: 56e65bed0eef
Create Date: 2026-08-31 15:16:01.938082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '797c95261056'
down_revision: Union[str, None] = '56e65bed0eef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dealer_access', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('listings', sa.Column('fair_value', sa.Float(), nullable=True))
    op.add_column('listings', sa.Column('value_low', sa.Float(), nullable=True))
    op.add_column('listings', sa.Column('value_high', sa.Float(), nullable=True))
    op.add_column('listings', sa.Column('margin', sa.Float(), nullable=True))
    op.add_column('listings', sa.Column('comps_used', sa.Integer(), nullable=True))
    op.add_column('listings', sa.Column('comp_step', sa.String(length=64), nullable=True))
    op.add_column('listings', sa.Column('comp_scope', sa.String(length=24), nullable=True))
    op.add_column('listings', sa.Column('comp_expanded', sa.Boolean(), nullable=True))
    op.add_column('listings', sa.Column('confidence', sa.String(length=8), nullable=True))
    op.add_column('listings', sa.Column('is_underpriced', sa.Boolean(), nullable=False,
                            server_default=sa.text('false')))
    op.add_column('listings', sa.Column('days_to_sell', sa.Float(), nullable=True))
    op.create_index(op.f('ix_listings_confidence'), 'listings', ['confidence'], unique=False)
    op.create_index(op.f('ix_listings_is_underpriced'), 'listings', ['is_underpriced'], unique=False)
    op.create_index(op.f('ix_listings_margin'), 'listings', ['margin'], unique=False)
    op.add_column('sales', sa.Column('source', sa.String(length=12), nullable=False,
                        server_default='derived'))
    op.create_index(op.f('ix_sales_source'), 'sales', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_source'), table_name='sales')
    op.drop_column('sales', 'source')
    op.drop_index(op.f('ix_listings_margin'), table_name='listings')
    op.drop_index(op.f('ix_listings_is_underpriced'), table_name='listings')
    op.drop_index(op.f('ix_listings_confidence'), table_name='listings')
    op.drop_column('listings', 'days_to_sell')
    op.drop_column('listings', 'is_underpriced')
    op.drop_column('listings', 'confidence')
    op.drop_column('listings', 'comp_expanded')
    op.drop_column('listings', 'comp_scope')
    op.drop_column('listings', 'comp_step')
    op.drop_column('listings', 'comps_used')
    op.drop_column('listings', 'margin')
    op.drop_column('listings', 'value_high')
    op.drop_column('listings', 'value_low')
    op.drop_column('listings', 'fair_value')
    op.alter_column('dealer_access', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
